# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'helm-file-utils'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-MB8JLN4696'

menu:
- {name: 'About Helm File Utils',   url: 'about-futl.html'}
- {name: 'About True North',   url: 'about-tn.html'}
- {name: 'Archived Posts', url: 'archive.html'}
- {name: 'Contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/true-north-engineering'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/company/tn-hr/'}
- {icon: 'envelope',   link: 'mailto:l.info@true-north.hr'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'More related posts:'

post_date_prefix: 'Written on'
